### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by nightmare199x** [mhqb365/quack-quack-game#1]
Error when running? please check these error:

ERROR TypeError: Cannot read properties of undefined (reading 'duck')
    at /root/quack-quack-game/quack.js:72:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by mhqb365** [comment]
get new access token first, running terminal + quack game both bro, try it

**Comment by nightmare199x** [comment]
> get new access token first, running terminal + quack game both bro, try it

thanks, it turns out the token was changed, it's not permernantly token?

**Comment by mhqb365** [comment]
yep, access token will change when you open new tab game, server game update or expired after 5days
