### ISSUE TITLE
Mình bị lỗi khi chạy

### ISSUE THREAD

**Issue by geznews** [mhqb365/quack-quack-game#10]
Chào bạn, mình bị lỗi này khi chạy, làm thế nào để fix vậy ạ
<img width="1335" alt="Screenshot 2024-06-05 at 08 54 06" src="https://github.com/mhqb365/quack-quack-game/assets/109203801/d72f93da-8407-45c3-af72-319d52e1cdf3">

**Comment by mhqb365** [comment]
Bạn thử tắt Tool đi rồi mở lại nhé, tắt game luôn và chỉ để Tool chạy càng tốt nhé

**Comment by geznews** [comment]
Mình đã thử nhưng vẫn bị lỗi tương tự như trên

**Comment by mhqb365** [comment]
bạn thử cho sleepTime trong config.json thành 3 hoặc lớn hơn nhé

**Comment by geznews** [comment]
mình đã thử nhưng vẫn bị ạ
<img width="1322" alt="Screenshot 2024-06-06 at 16 50 15" src="https://github.com/mhqb365/quack-quack-game/assets/109203801/60c66c57-b160-440f-97b3-a403d68aa8c2">

**Comment by mhqb365** [comment]
bạn có 15 tổ lận á ???

**Comment by lqdat** [comment]
lỗi này là do chạy 2 lệnh gọi á , tắt hết hoàn toàn tool đi , thử chạy lại chỉnh file config.json chỗ sleep time thành 3 hoặc 5, để tránh khi chưa có trứng mà có lệnh lấy trứng

**Comment by mhqb365** [comment]
mình đoán do bạn ấy set nest = 15
mà trong code có đoạn: nếu số tổ request api lấy được mà ít hơn nest config thì gọi api lại, đến khi số tổ request api bằng số nest config mới thôi 😂

**Comment by lqdat** [comment]
> mình đoán do bạn ấy set nest = 15 mà trong code có đoạn: nếu số tổ request api lấy được mà ít hơn nest config thì gọi api lại, đến khi số tổ request api bằng số nest config mới thôi 😂

ừ đúng rồi chỗ đó ấy nên để nest mặc định thôi đường nào chả lấy nest ra từ api mà , mà có đúng 15 tổ k nhỉ nếu đúng thì hơi khủng đấy 😂
