### ISSUE TITLE
Này bị sao á ad

### ISSUE THREAD

**Issue by VinnH2t** [mhqb365/quack-quack-game#12]
![Screenshot 2024-06-08 153636](https://github.com/mhqb365/quack-quack-game/assets/172107534/277d6a4a-14c8-4c00-a9f8-d7fdf76cad55)

**Comment by mhqb365** [comment]
bạn đọc lại hướng dẫn ở phần README giúp mình nhé, mình ghi khá chi tiết, cách dùng của bạn có thể là ở phiên bản đầu tiên, giờ không còn sử dụng nữa
