### ISSUE TITLE
Lỗi zịt zàng!

### ISSUE THREAD

**Issue by xupitan1102** [mhqb365/quack-quack-game#14]
![Screenshot 2024-06-10 123417](https://github.com/mhqb365/quack-quack-game/assets/22125602/ceaa97f5-768a-4391-9f2a-f668c86e1c95)
Mình bị lỗi này, quan sát thấy thi thoảng lỗi con zịt r nó bị như vậy, kb là cái j :(

**Comment by mhqb365** [comment]
lỗi này lên v4 fix rồi nhé, chờ thêm mấy hôm để stable v4, hoặc vào branch v4-beta, cám ơn bạn
