### ISSUE TITLE
Lỗi Node quack 2

### ISSUE THREAD

**Issue by DucAnh812** [mhqb365/quack-quack-game#15]
Chạy Node quack 2 báo lost connect liên tục à bác ơi. Xong 1 tí là dừng luôn
Error 400

**Comment by mhqb365** [comment]
ông có chỉnh gì trong config.json hem?

**Comment by DucAnh812** [comment]
> ông có chỉnh gì trong config.json hem?

Ko âu sếp, tải về, lấy file token từ bộ cũ dán qua rùi chạy thui à. Chạy cái Node quack thì ngon lành, nhưng cái Quack 2 là bị

**Comment by mhqb365** [comment]
để tui theo dõi thêm, cám ơn ông nhen

**Comment by DucAnh812** [comment]
![image](https://github.com/mhqb365/quack-quack-game/assets/56624911/dc89ceeb-a1a2-4fd5-9aa7-c02190585df0)
đầu tiên báo lỗi này nè bác

**Comment by mhqb365** [comment]
mình cám ơn ạ

**Comment by DucAnh812** [comment]
![image](https://github.com/mhqb365/quack-quack-game/assets/56624911/26c35e6e-36d0-4369-86ef-162a3e0d4bbd)

**Comment by mhqb365** [comment]
quên nói bạn node quack 2 chưa ổn định, còn lỗi nhiều lắm, tối nay mới fix được, ban ngày sửa laptop 😍

**Comment by DungDev1204** [comment]
![image](https://github.com/mhqb365/quack-quack-game/assets/89788261/d96c9073-287a-4ffc-afb8-a6e57c294a9c)
Tôi cũng bj lỗi giống bác trên . được bảo chụp màn hình để fix

**Comment by mhqb365** [comment]
Cám ơn bạn ạ, tối nay mình sẽ fix các lỗi liên quan node quack 2 nhé, ban ngày mình sửa laptop nên chưa fix được

**Comment by DungDev1204** [comment]
Tool bạn rất hay. mong bạn phát triển nó và duy trì nó nhé. nếu cần thì cứ kêu gọi donate nhé

**Comment by mhqb365** [comment]
> Tool bạn rất hay. mong bạn phát triển nó và duy trì nó nhé. nếu cần thì cứ kêu gọi donate nhé

mình cám ơn ạ 😍

**Comment by DucAnh812** [comment]
> Cám ơn bạn ạ, tối nay mình sẽ fix các lỗi liên quan node quack 2 nhé, ban ngày mình sửa laptop nên chưa fix được

Cảm ơn bác đã chia sẻ

**Comment by haden2911** [comment]
Anh ơi em có CFO rồi, anh có thể nào làm 1 cái code chỉ có riêng tự động lụm vịt vàng được không ạ :(((

**Comment by DThanh0** [comment]
> Anh ơi em có CFO rồi, anh có thể nào làm 1 cái code chỉ có riêng tự động lụm vịt vàng được không ạ :(((

tui thấy ổng có để quack 1l à lụm vịt vàng mà

**Comment by haden2911** [comment]
> > Anh ơi em có CFO rồi, anh có thể nào làm 1 cái code chỉ có riêng tự động lụm vịt vàng được không ạ :(((
> 
> tui thấy ổng có để quack 1l à lụm vịt vàng mà

tui thử thấy cái nào cũng có nhặt trứng hết mà chạy song song với cái CFO là nó sẽ báo lỗi duplicate á :((

**Comment by DungDev1204** [comment]
> > > Anh ơi em có CFO rồi, anh có thể nào làm 1 cái code chỉ có riêng tự động lụm vịt vàng được không ạ :(((
> > 
> > 
> > tui thấy ổng có để quack 1l à lụm vịt vàng mà
> 
> tui thử thấy cái nào cũng có nhặt trứng hết mà chạy song song với cái CFO là nó sẽ báo lỗi duplicate á :((

Thì phải có vịt vàng mới lum được chứ. chứ nó có spawn liên tục đâu

**Comment by haden2911** [comment]
> Thì phải có vịt vàng mới lum được chứ. chứ nó có spawn liên tục đâu

đợi tới lúc có vịt vàng là cái tool nó tự dừng do lỗi nhặt trứng thường không được rồi ạ :(( có cách nào tách cái lụm mỗi vịt vàng được không ạ

**Comment by DungDev1204** [comment]
> > Thì phải có vịt vàng mới lum được chứ. chứ nó có spawn liên tục đâu
> 
> đợi tới lúc có vịt vàng là cái tool nó tự dừng do lỗi nhặt trứng thường không được rồi ạ :(( có cách nào tách cái lụm mỗi vịt vàng được không ạ

trong tool có đấy bạn ơi. tôi vẫn lum được bth . làm theo từng bước hướng dẫn ấy. đọc kĩ xíu là được

**Comment by haden2911** [comment]
> trong tool có đấy bạn ơi. tôi vẫn lum được bth . làm theo từng bước hướng dẫn ấy. đọc kĩ xíu là được

oke ông ơi, tui vô sửa trong code được rồi ^^

**Comment by AnhAnhii** [comment]
Đợi fix node Quack 2 tool hay nha bạn ơi, ủng hộ nhiệt tình tối ưu và ra thêm chức năng khác nếu có là đẹp luôn á

**Comment by mhqb365** [comment]
cám ơn mọi người đã ủng hộ ạ 😍

**Comment by mhqb365** [comment]
> > trong tool có đấy bạn ơi. tôi vẫn lum được bth . làm theo từng bước hướng dẫn ấy. đọc kĩ xíu là được
> 
> oke ông ơi, tui vô sửa trong code được rồi ^^

cho mình xin cách bạn ơi 😍

**Comment by haden2911** [comment]
> > > trong tool có đấy bạn ơi. tôi vẫn lum được bth . làm theo từng bước hướng dẫn ấy. đọc kĩ xíu là được
> > 
> > 
> > oke ông ơi, tui vô sửa trong code được rồi ^^
> 
> cho mình xin cách bạn ơi 😍

anh lại trêu em 😂 ngồi vọc xong mới thấy là trong tool anh làm sẵn rồi, bị cái nếu chỉ chạy mỗi quack 1 thì khi chúc bạn may mắn lần sau là nó treo luôn tool nè anh

**Comment by mhqb365** [comment]
> > > > trong tool có đấy bạn ơi. tôi vẫn lum được bth . làm theo từng bước hướng dẫn ấy. đọc kĩ xíu là được
> > > 
> > > 
> > > oke ông ơi, tui vô sửa trong code được rồi ^^
> > 
> > 
> > cho mình xin cách bạn ơi 😍
> 
> anh lại trêu em 😂 ngồi vọc xong mới thấy là trong tool anh làm sẵn rồi, bị cái nếu chỉ chạy mỗi quack 1 thì khi chúc bạn may mắn lần sau là nó treo luôn tool nè anh

okie bạn ơi, đã tiếp nhận, fix sớm nhất có thể nhen, tại ban ngày tui sửa laptop, tối mới về code vì đam mê 🤣

**Comment by haden2911** [comment]
> > > > > trong tool có đấy bạn ơi. tôi vẫn lum được bth . làm theo từng bước hướng dẫn ấy. đọc kĩ xíu là được
> > > > 
> > > > 
> > > > oke ông ơi, tui vô sửa trong code được rồi ^^
> > > 
> > > 
> > > cho mình xin cách bạn ơi 😍
> > 
> > 
> > anh lại trêu em 😂 ngồi vọc xong mới thấy là trong tool anh làm sẵn rồi, bị cái nếu chỉ chạy mỗi quack 1 thì khi chúc bạn may mắn lần sau là nó treo luôn tool nè anh
> 
> okie bạn ơi, đã tiếp nhận, fix sớm nhất có thể nhen, tại ban ngày tui sửa laptop, tối mới về code vì đam mê 🤣

dạ em cảm ơn

**Comment by mhqb365** [comment]
đã fix node quack 2 nhé mọi người, clone nhánh master về nhé
