### ISSUE TITLE
node quack 2 lỗi

### ISSUE THREAD

**Issue by hoangvu1110** [mhqb365/quack-quack-game#18]
![Screenshot 2024-06-12 201320](https://github.com/mhqb365/quack-quack-game/assets/66820445/d0c532b9-22e8-4e20-916a-360a9958e7c3)

**Comment by mhqb365** [comment]
đã fix, bạn clone nhánh master về nhé

**Comment by hoangvu1110** [comment]
Clone nhánh master là như thế nào ạ ?

**Comment by mhqb365** [comment]
bạn cứ vào trang chủ tool tải code về nhé
