### ISSUE TITLE
Lỗi hiển thị

### ISSUE THREAD

**Issue by sangnekk** [mhqb365/quack-quack-game#2]
![image](https://github.com/mhqb365/quack-quack-game/assets/85666619/f966a1a6-a86e-4e41-b92c-4f8fe7c4d83e)
số trứng đã thu thập rồi vẫn hiển thị khiến thông tin hiển thị ngày càng nhiều và ngốn ram

**Comment by mhqb365** [comment]
bạn tải commit mới nhất nhé, đã fix lỗi này ở commit mới nhất
