### ISSUE TITLE
Mở zịt chưa tối ưu!

### ISSUE THREAD

**Issue by xupitan1102** [mhqb365/quack-quack-game#21]
![image](https://github.com/mhqb365/quack-quack-game/assets/22125602/51cf90eb-8c31-4c64-a59f-e23c36046deb)
1. Chưa check loại trứng đúng, vd với 4 ổ chỉ mở Rare 3* với 4* thôi, mà tốt nhất cho chọn loại trứng để mở ở file config (Rare 4* tương đương với type 6), mình thường chỉ mở 4*.
2. So sánh vịt chưa ổn, vd mục đích ở 4 ổ là full 1 dòng Legend, như vậy nếu check full vịt có 1 dòng Legend r thì stop chức năng ấp lại :), nếu còn con nào 2 rare trở xuống thì del để chờ ấp ra vịt Legend.

**Comment by mhqb365** [comment]
cám ơn bạn đã góp ý ạ, mình sẽ thêm vào sớm nhất có thể ạ

**Comment by mhqb365** [comment]
mình vừa fix ý số 1 của bạn nhưng mà sẽ tự động đúng với số tổ luôn ạ

lý do trước đó bị sai là mình chưa vào xem hướng dẫn của game nên không biết số vịt số trứng đều có quy luật rõ ràng
trước đó mình toàn đoán mò qua request API 😅

ý số 2 mình sẽ thêm sau, đại loại là sẽ chọn ưu tiên giữa vịt rare hay vịt legend hoặc đại loại thế

cám ơn bạn đã góp ý ạ 😍

**Comment by xupitan1102** [comment]
> mình vừa fix ý số 1 của bạn nhưng mà sẽ tự động đúng với số tổ luôn ạ
> 
> lý do trước đó bị sai là mình chưa vào xem hướng dẫn của game nên không biết số vịt số trứng đều có quy luật rõ ràng trước đó mình toàn đoán mò qua request API 😅
> 
> ý số 2 mình sẽ thêm sau, đại loại là sẽ chọn ưu tiên giữa vịt rare hay vịt legend hoặc đại loại thế
> 
> cám ơn bạn đã góp ý ạ 😍

Ko có j bác ơi, bác add thêm quả điểm danh hàng ngày nữa thì ngon :))

**Comment by anluong1102** [comment]
Hóng bác fix code từng giờ để xem có update gì về vụ lum Ton không

**Comment by mhqb365** [comment]
> Hóng bác fix code từng giờ để xem có update gì về vụ lum Ton không

tất nhiên là không có lụm TON rồi, vì lý do bảo mật 🔐

**Comment by mhqb365** [comment]
> ![image](https://private-user-images.githubusercontent.com/22125602/339170309-51cf90eb-8c31-4c64-a59f-e23c36046deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1ODU5NDYsIm5iZiI6MTcxODU4NTY0NiwicGF0aCI6Ii8yMjEyNTYwMi8zMzkxNzAzMDktNTFjZjkwZWItOGMzMS00YzY0LWE1OWYtZTIzYzM2MDQ2ZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDAwNTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDUwM2Y2YmI4YjUyYWRlNmNlOTQxYmM1NzBjOGY5ZDg1MDcwNzcwZmU1NDY0YWFmNzA4OTE4YWY4NjY0MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6LejAoGGXwMtgHYxv1FaVyKQRPLuFOHZSuXOm2FBuoo)
> 
> 1. Chưa check loại trứng đúng, vd với 4 ổ chỉ mở Rare 3* với 4* thôi, mà tốt nhất cho chọn loại trứng để mở ở file config (Rare 4* tương đương với type 6), mình thường chỉ mở 4*.
> 2. So sánh vịt chưa ổn, vd mục đích ở 4 ổ là full 1 dòng Legend, như vậy nếu check full vịt có 1 dòng Legend r thì stop chức năng ấp lại :), nếu còn con nào 2 rare trở xuống thì del để chờ ấp ra vịt Legend.

Xong ý số 2 nhé, nếu để rareEggToHatch trong config.json bằng 0 thì sẽ tự động chọn cái rare hiếm nhất
