### ISSUE TITLE
Only Zịt Zàng vẫn bị lỗi treo ạ

### ISSUE THREAD

**Issue by haden2911** [mhqb365/quack-quack-game#22]
![image](https://github.com/mhqb365/quack-quack-game/assets/172478363/6cab059e-53ea-4ed5-9df3-060933da4f45)
Lụm được trứng hay pepet thì k sao nhưng cứ chúc bạn may mắn lần sau là nó treo vậy luôn ạ @@

**Comment by mhqb365** [comment]
cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ

**Comment by haden2911** [comment]
> cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ

dạ em cảm ơn a

**Comment by DungDev1204** [comment]
> cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ

Nếu được. Bác nghiên cứu lụm TON nhé. Hôm qua vịt vàng mình thấy có TON mà nó k lụm. tiếc quá 😂

**Comment by mhqb365** [comment]
> > cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ
> 
> Nếu được. Bác nghiên cứu lụm TON nhé. Hôm qua vịt vàng mình thấy có TON mà nó k lụm. tiếc quá 😂

cái này hơi căng, nên xin bỏ qua request này ạ

**Comment by mhqb365** [comment]
> > cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ
> 
> dạ em cảm ơn a

bạn tải code mới về thử lại nhé, fix treo zịt zàng only mode rồi á

**Comment by haden2911** [comment]
> > > cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ
> > 
> > 
> > dạ em cảm ơn a
> 
> bạn tải code mới về thử lại nhé, fix treo zịt zàng only mode rồi á

dạ để em thử lại ạ

**Comment by mhqb365** [comment]
> > > > cám ơn bạn đã gửi issue ạ, fix xong mình sẽ thông báo liền ạ
> > > 
> > > 
> > > dạ em cảm ơn a
> > 
> > 
> > bạn tải code mới về thử lại nhé, fix treo zịt zàng only mode rồi á
> 
> dạ để em thử lại ạ

ok chưa bạn ơi?

**Comment by mhqb365** [comment]
ok mình cám ơn nhé, close issue đây 😍
