### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sangnekk** [mhqb365/quack-quack-game#3]
![image](https://github.com/mhqb365/quack-quack-game/assets/85666619/c9465afe-2c3d-4cbd-b1df-aa8d92f04870)

**Comment by mhqb365** [comment]
để mình theo dõi thêm về lỗi này nhé, mình chưa gặp lỗi này á, 1 gợi ý thêm là khi bạn chạy tool xong thì bạn click vào của sổ Quack game để nó ở trên cửa sổ tool sẽ cải thiện hơn

**Comment by sangnekk** [comment]
mình có treo cả 2 tab ấy ạ thì treo 1 hồi là dính

**Comment by sangnekk** [comment]
![image](https://github.com/mhqb365/quack-quack-game/assets/85666619/949acd04-9731-4960-b4fa-1e6fb01bc3f7)
lại thêm lỗi mới r ạ

**Comment by mhqb365** [comment]
mình mới thay đổi cách dùng, bạn chịu khó đọc README giúp mình nhen 🥹

**Comment by sangnekk** [comment]
à mình cảm ơn mình đọc không kĩ
