### ISSUE TITLE
layEgg error status 400

### ISSUE THREAD

**Issue by Artyorm** [mhqb365/quack-quack-game#30]
Thoi gian chay : [ 00:00:55:34 ]
Tong thu hoach : [ 1923.00 EGG 🥚 ] [ 0.00 PET 🐸 ]

[ GOLDEN DUCK 🐥 ] : [ 2 🐥 ] | 1236s nua gap
[ 3 NEST 🌕 ] : [ 2444328, 2444329, 2444330 ]

layEgg error
status 400
layEggData 2 error THIS_DUCK_NOT_ENOUGH_TIME_TO_LAY
Da thu hoach [ NEST 🌕 2444329 ] : [ EGG 🥚 Common * ]
Da thu hoach [ NEST 🌕 2444328 ] : [ EGG 🥚 Common * ]
collectEgg error
status 400
collectEggData error THIS_NEST_DONT_HAVE_EGG_AVAILABLE

**Comment by mhqb365** [comment]
fix soon, tks u much 😍

**Comment by mhqb365** [comment]
how many your nest, duck? and what mode u use?

**Comment by mhqb365** [comment]
After the error messages, the tool will continue to work, you don't need to worry

**Comment by Artyorm** [comment]
tks u much 😍
