### ISSUE TITLE
Nâng điều kiện ấp

### ISSUE THREAD

**Issue by 4Blank4** [mhqb365/quack-quack-game#31]
Cảm ơn bạn. Tool rất hay!

Hiện tại mình chạy quack 2 đến phần 15 con vịt đều có 1 bộ phận là rare thì nó gần như không thể tăng lên nữa. Không biết làm sao để mình đổi điều kiện của nó thành 2 bộ phận hoặc cao hơn nữa. Có gì bạn hướng dẫn giúp với.

P/S: Mình không rành code lắm nên nếu phần này có đề cập sẵn hoặc đơn giản quá thì thông cảm mình nha.

Cám ơn bạn lần nữa!!!

**Comment by mhqb365** [comment]
Yo, cám ơn lời khen của bạn nhé

Còn về phần vịt này là do game quy định, bạn xem whitepaper của game sẽ rõ nhé
Whitepaper game đây 👉 https://whitepaper.quackquack.games/quack-quack/game-elements/ducks
