### ISSUE TITLE
lỗi này sao á anh

### ISSUE THREAD

**Issue by phamnam2308** [mhqb365/quack-quack-game#33]
![Capture](https://github.com/mhqb365/quack-quack-game/assets/106069982/f1db0886-bcbc-4605-bac0-8ae1e6a3b50d)
![488472ec-c349-43de-a54f-acc8d2f513df](https://github.com/mhqb365/quack-quack-game/assets/106069982/df733e96-c54c-4f8a-804e-2e954d95671f)

**Comment by phamnam2308** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/106069982/340022202-f1db0886-bcbc-4605-bac0-8ae1e6a3b50d.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Nzk0MDQsIm5iZiI6MTcxODQ3OTEwNCwicGF0aCI6Ii8xMDYwNjk5ODIvMzQwMDIyMjAyLWYxZGIwODg2LWJjYmMtNDYwNS1iYWMwLThhZTFlNmEzYjUwZC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxOTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzIyZDViYjRhY2NiOTcyNjc4NjU1ZjE3NWU2OGJjMjY3Nzg0YjBmYWQ4NWZmMjNiYTAyNjMwZmQ4ZDJkNDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oBo3tqmLQQVHP_PVTAcN88Z5aMN28q7TF47jbk59KJo)
![image](https://github.com/mhqb365/quack-quack-game/assets/106069982/fe512b46-2bcf-42db-b8e4-d0094b79644f)

**Comment by mhqb365** [comment]
có ít vịt quá, đẻ trứng hông kịp, ấp thêm vài con nữa đi, min 10 com may ra kịp
