### ISSUE TITLE
Tôi phải sử lí lỗi này như thế nào ? Đã làm theo cách bước. khi tải code mới về chạy thì bị dính lỗi này. Nhưng lần trước đều chạy bình thường 

### ISSUE THREAD

**Issue by DungDev1204** [mhqb365/quack-quack-game#37]
![Screenshot 2024-06-17 085257](https://github.com/mhqb365/quack-quack-game/assets/89788261/bc27755b-de3d-41b3-96e7-8eb68caf01dd)

**Comment by mhqb365** [comment]
bạn xem lại file config.json nhé, báo lỗi ở đó

**Comment by DungDev1204** [comment]
> bạn xem lại file config.json nhé, báo lỗi ở đó

ok. mình fix được rồi. cảm ơn nhé
