### ISSUE TITLE
Cần thêm tính năng chạy với proxy

### ISSUE THREAD

**Issue by kamkuakuay** [mhqb365/quack-quack-game#38]
Hiện tại code chạy rất tốt và ok tối ưu được nhiều thứ tuy nhiên lên thêm phần proxy thì sẽ đảm bảo sự an toàn của các tài khoản hơn tránh tình trạng bị ban.

**Comment by mhqb365** [comment]
![image](https://github.com/mhqb365/quack-quack-game/assets/68866600/dcf5d820-35b6-45a5-b177-9a4952e501ae)
ý bạn là cái này hử? 🤣
opensrc mà nhiều tính năng quá có quá đáng lắm khum 🤣

**Comment by kamkuakuay** [comment]
đấy là check proxy thôi ý của mình là nếu có nhiều acc thì sẽ phải chạy trên các proxy khác nhau chứ chạy nhiều acc mà cùng 1 ip thì dễ bị ban lắm lên tool của mình thêm chức năng chạy vs proxy list là ok rồi

**Comment by mhqb365** [comment]
> đấy là check proxy thôi ý của mình là nếu có nhiều acc thì sẽ phải chạy trên các proxy khác nhau chứ chạy nhiều acc mà cùng 1 ip thì dễ bị ban lắm lên tool của mình thêm chức năng chạy vs proxy list là ok rồi

thì mình không biết proxy chớt hay sống nên mới làm thêm 1 cái check proxy đó, cơ mà mình không định thêm proxy vào cho cái tool lỏ này đâu, ai muốn thì bê code về phát triển thêm 😍

**Comment by mhqb365** [comment]
> mà bạn làm sửa laptop sao lập trình siêu thế, mình cũng đang mày mò mà ko biết bắt đầu từ đâu, xin bạn ít kinh nghiệm với

mình copy code trên google về run, thử thay đổi biến rồi run, rồi bla bla rồi thành kết quả 😍

**Comment by kamkuakuay** [comment]
ok cảm ơn bạn nhiều
