### ISSUE TITLE
Chọn rare trứng nhưng không ấp trứng xịn

### ISSUE THREAD

**Issue by Alexkhang93** [mhqb365/quack-quack-game#39]
Mình có set rare egg từ 0-8 ( mình có 5 tổ) nhưng tool nó ko ấp trứng rare ******* , cái dòng FARM QUALIFIED NO NEED HATCH HIỆN LÊN NÈ BẠN...
![messageImage_1718694765676](https://github.com/mhqb365/quack-quack-game/assets/173137147/71fc063d-ac12-466b-9643-68e49dc82e9e)

**Comment by mhqb365** [comment]
vịt bạn max level rồi, bạn check ở đây nhé 👉 https://whitepaper.quackquack.games/quack-quack/game-elements/ducks
