### ISSUE TITLE
Tôi chỉnh sửa code để claim TON

### ISSUE THREAD

**Issue by DungDev1204** [mhqb365/quack-quack-game#5]
Nếu tôi clone code về sửa để claim TON thì tôi cần điều chỉnh như nào ? Mong bác chỉ thêm

**Comment by AnhAnhii** [comment]
Hóng về chức năng này, rất mong bác chủ tool ra chức năng claim ton

**Comment by mhqb365** [comment]
tui sẽ nghiên cứu tính năng này
